sudo: false
language: python
python:
   - "3.5"
before_install:
   - ln -s install/funyun_tool.sh ./funyun_tool
   - ./funyun_tool create_scripts
   - ./funyun_tool init
   - export root_dir="$(python -c 'import sys;print(sys.prefix)')"
   - ./funyun_tool config root_dir $root_dir
   - ./funyun_tool config var_dir ${root_dir}/var
   - ./funyun_tool config tmp_dir ${root_dir}/var/tmp
   - ./funyun_tool config log_dir ${root_dir}/var/log
   - ./funyun_tool config python system
   - ./funyun_tool config prometheus system
   - ./funyun_tool config alertmanager system
   - ./funyun_tool config node_exporter system
   - ./funyun_tool config pushgateway system
   - ./funyun_tool config all
   - ./funyun_tool make_dirs
   - ./funyun_tool install
install:
   - pip install -U setuptools
   - pip install -r requirements.txt
   - pip install -e .
before_script:
   - funyun_env coverage run -m funyun.cli
   - export COVERAGE_PROCESS_START="${PWD}/.coveragerc"
   - funyun_env funyun config secret_key
   - funyun_env funyun config secret_key blahblahblah
   - funyun_env funyun config
   - funyun_env funyun create_instance
   - funyun_env funyun set_htpasswd
   - funyun_env funyun create_test_files
script:
   - funyun_env -v start
   - export log_dir=$(funyun_env funyun config log)
   - ./test_targets.sh
   - funyun_env stop
   - cat ${log_dir}/nginx/error.log
after_success:
   - funyun_env funyun test_logging
   - funyun_env funyun config blah Bob_LobLaw
   - funyun_env funyun config --vartype=list mylist "[1,2,3]"
   - funyun_env funyun config var /tmp/funyunvar
   - export FUNYUN_SUPERVISORD_START_SERVER=True
   - funyun_env funyun config supervisord_start_nginx False
   - export FUNYUN_SUPERVISORD_START_SERVER=False
   - funyun_env funyun config gunicorn_unix_socket False
   - funyun_env funyun config nginx_unix_socket True
   - funyun_env funyun create_instance --force
   - funyun_env funyun set_htpasswd --force
   - funyun_env funyun config --delete
   - coverage combine
   - cp /tmp/.coverage .
   - bash <(curl -s https://codecov.io/bash) -X gcov
